language: go
go:
  - 1.1
  - 1.2
  - tip
before_script:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go build -v ./...
script:
  - go test -v ./...
  - ./coveralls
notifications:
  email:
    recipients:
      - toqoz403@gmail.com
    on_success: change
    on_failure: always
